"""
Robustness check: does winsorising the most extreme 0.1% of hourly
log-returns change the K=3 regime structure?

Fits K=3 raw and winsorised on the SAME panel and tabulates the deltas.

IMPORTANT (provenance): the paper's window is 2 Oct 2025 00:00 UTC to
28 Apr 2026 08:00 UTC, but hourly candles for that whole window cannot be
re-fetched -- the Hyperliquid ``candleSnapshot`` endpoint retains only ~5,000
recent candles per interval -- and the full-window hourly panel is not part of
this package.  The panel shipped with this repository
(``data/processed/panel_BTC_subsample.csv``) covers 3 Dec 2025 - 28 Apr 2026
(T = 3,507), and that is the window this script fits by default.
``output/robustness.json`` is computed on exactly that sub-sample.

Usage
-----
    python -m regime_engine.robustness [--panel PATH] [--out DIR]
"""
from __future__ import annotations

import argparse
import json
import pathlib

import numpy as np

from .hmm import GaussianHMM
from .panel import load_panel
from .paths import DEFAULT_OUT, DEFAULT_PANEL

HMM_SEED = 45
HMM_N_STARTS = 8
HMM_N_ITER = 150

OUT = DEFAULT_OUT


def describe_fit(hmm: GaussianHMM, T: int) -> dict:
    """Summarise a fit, in the paper's sigma-ascending state order.

    ``hmm.fit`` already returns states in that order; the sort below is applied
    anyway so the artifact does not depend on where the model came from.

    The transition cells the paper quotes are reported under *names* rather
    than positions. A positional key such as ``A12`` changes meaning with the
    labelling rule -- under a mu-ascending sort its row need not be the
    low-volatility state -- while a named key does not.
    """
    order = np.argsort(hmm.sigma)
    mu = np.asarray(hmm.mu)[order]
    sigma = np.asarray(hmm.sigma)[order]
    A = np.asarray(hmm.A)[np.ix_(order, order)]
    stationary = np.asarray(hmm.stationary_distribution())[order]
    durations = np.asarray(hmm.expected_durations())[order]
    low, moderate, high = 0, 1, hmm.K - 1
    return {
        "state_order": "sigma ascending (0 = low, 1 = moderate, 2 = high volatility)",
        "mu_bps": [round(float(m * 1e4), 4) for m in mu],
        "sigma_bps": [round(float(s * 1e4), 4) for s in sigma],
        "ann_vol_pct": [round(float(s * np.sqrt(24 * 365) * 100), 2) for s in sigma],
        "diagA": [round(float(A[k, k]), 4) for k in range(hmm.K)],
        "A": [[round(float(A[i, j]), 6) for j in range(hmm.K)] for i in range(hmm.K)],
        "A_high_to_low": round(float(A[high, low]), 5),
        "A_high_to_moderate": round(float(A[high, moderate]), 5),
        "A_low_to_high": round(float(A[low, high]), 5),
        "sigma_rank": [int(r) for r in np.argsort(np.argsort(sigma))],
        "stationary": [round(float(p), 4) for p in stationary],
        "expected_dur_h": [round(float(d), 2) for d in durations],
        "logL": round(float(hmm.log_likelihood_), 2),
        "AIC": round(float(hmm.aic()), 2),
        "BIC": round(float(hmm.bic(T)), 2),
        "seed": HMM_SEED,
    }


def write_robustness_table(payload: dict, out_dir) -> pathlib.Path:
    """Write the winsorisation table, ``tables/table5_robustness.tex``.

    The table is generated from the fit rather than maintained by hand, so its
    columns always follow the sigma-ascending state order and the volatility
    labels used everywhere else in the package.
    """
    tab = pathlib.Path(out_dir) / "tables"
    tab.mkdir(parents=True, exist_ok=True)
    raw = payload["raw"]["ann_vol_pct"]
    win = payload["winsorised"]["ann_vol_pct"]
    T = payload["T"]
    t_tex = f"{T:,}".replace(",", "{,}")        # LaTeX thousands separator
    tex = (
        "% Generated by regime_engine.robustness -- do not edit by hand.\n"
        f"% Sub-period fit, T = {T:,}; {payload['winsor_n_clipped']} observations clipped.\n"
        "% Columns follow the sigma-ascending labelling of Section 2.1, so column k\n"
        "% is State k of the manuscript's regime-parameter table.\n"
        "\\begin{tabular}{lrrr}\n\\toprule\n"
        "Annualised $\\hat\\sigma$ & 1 low & 2 moderate & 3 high \\\\\n\\midrule\n"
        f"Raw ($T={t_tex}$) & " + " & ".join(f"{v:.1f}\\%" for v in raw) + " \\\\\n"
        "Winsorised (extreme 0.1\\%) & " + " & ".join(f"{v:.1f}\\%" for v in win)
        + " \\\\\n\\bottomrule\n\\end{tabular}\n"
    )
    path = tab / "table5_robustness.tex"
    path.write_text(tex)
    return path


def build_arg_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="python -m regime_engine.robustness",
        description="Winsorisation robustness check for the K=3 return HMM.",
    )
    ap.add_argument("--panel", metavar="PATH", default=str(DEFAULT_PANEL),
                    help=f"hourly panel (.csv or .parquet). Default: {DEFAULT_PANEL}")
    ap.add_argument("--out", metavar="DIR", default=str(DEFAULT_OUT),
                    help=f"output directory (default: {DEFAULT_OUT})")
    return ap


def main(argv=None):
    global OUT
    args = build_arg_parser().parse_args(argv)
    OUT = pathlib.Path(args.out).expanduser().resolve()
    OUT.mkdir(parents=True, exist_ok=True)

    panel_path = pathlib.Path(args.panel)
    if not panel_path.exists():
        raise SystemExit(
            f"panel not found: {panel_path}\n"
            "The paper's full window is no longer re-fetchable; pass --panel PATH "
            "to point at a panel you have."
        )
    panel = load_panel(panel_path)

    r = panel["log_return"].values
    T = len(r)
    print(f"panel : {panel_path}")
    print(f"T = {T}")
    print(f"window: {panel['time'].iloc[0]} -> {panel['time'].iloc[-1]}")
    print(f"return mean/std (bps): {r.mean()*1e4:.3f} / {r.std()*1e4:.3f}")
    print(f"return min/max (bps):  {r.min()*1e4:.1f} / {r.max()*1e4:.1f}")

    # ---- RAW fit (the "Raw" row of table5_robustness) ----
    print("\n[fit] RAW K=3 ...")
    hmm_raw = GaussianHMM(K=3, n_starts=HMM_N_STARTS, n_iter=HMM_N_ITER,
                          random_state=HMM_SEED).fit(r)
    raw = describe_fit(hmm_raw, T)
    print(json.dumps(raw, indent=2))

    # ---- WINSORISED fit: clip most extreme 0.1% (0.05% per tail) ----
    lo, hi = np.quantile(r, [0.0005, 0.9995])
    n_clip = int((r < lo).sum() + (r > hi).sum())
    r_w = np.clip(r, lo, hi)
    print(f"\n[winsorise] clip to [{lo*1e4:.1f}, {hi*1e4:.1f}] bps; {n_clip} obs clipped "
          f"({100*n_clip/T:.3f}%)")
    print("[fit] WINSORISED K=3 ...")
    hmm_w = GaussianHMM(K=3, n_starts=HMM_N_STARTS, n_iter=HMM_N_ITER,
                        random_state=HMM_SEED).fit(r_w)
    win = describe_fit(hmm_w, T)
    print(json.dumps(win, indent=2))

    result = {
        "T": T,
        "panel_source": str(panel_path),
        "window": [str(panel["time"].iloc[0]), str(panel["time"].iloc[-1])],
        "return_mean_bps": round(float(r.mean() * 1e4), 4),
        "return_std_bps": round(float(r.std() * 1e4), 4),
        "return_min_bps": round(float(r.min() * 1e4), 1),
        "return_max_bps": round(float(r.max() * 1e4), 1),
        "winsor_bounds_bps": [round(float(lo * 1e4), 2), round(float(hi * 1e4), 2)],
        "winsor_n_clipped": n_clip,
        "winsor_pct_clipped": round(100 * n_clip / T, 4),
        "raw": raw,
        "winsorised": win,
        "std_after_winsor_bps": round(float(r_w.std() * 1e4), 4),
    }
    (OUT / "robustness.json").write_text(json.dumps(result, indent=2))
    print(f"\n[saved] {OUT/'robustness.json'}")
    table = write_robustness_table(result, OUT)
    print(f"[LaTeX] wrote {table}")

    # quick side-by-side
    print("\n=== RAW vs WINSORISED (K=3) ===")
    print(f"{'metric':<22}{'raw':>22}{'winsorised':>22}")
    for key in ("sigma_bps", "ann_vol_pct", "diagA", "stationary"):
        print(f"{key:<22}{str(raw[key]):>22}{str(win[key]):>22}")
    print(f"{'A high->moderate':<22}{raw['A_high_to_moderate']:>22}{win['A_high_to_moderate']:>22}")
    print(f"{'A high->low':<22}{raw['A_high_to_low']:>22}{win['A_high_to_low']:>22}")
    print(f"{'logL':<22}{raw['logL']:>22}{win['logL']:>22}")
    print(f"{'BIC':<22}{raw['BIC']:>22}{win['BIC']:>22}")
    return result


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# Model selection beyond K = 3
# ---------------------------------------------------------------------------

#: K values the paper reports. K=2 and K=3 are the main comparison; K=4 and K=5
#: check whether more states are supported and whether such models can be
#: estimated stably. On this sample they can: all four converge from 40 starts.
SELECTION_KS = (2, 3, 4, 5)

#: More starts than the K<=3 default. The extra states multiply the local optima,
#: and a K=4 result from a handful of starts would not be worth reporting.
SELECTION_N_STARTS = 40
SELECTION_N_ITER = 300


def n_free_parameters(K: int) -> int:
    """``|theta_K| = K^2 + 2K - 1``, the count stated with the Gaussian HMM in Section 2.1."""
    return K * K + 2 * K - 1


def preferred_k(records):
    """The K with the lowest finite BIC; ties go to the smaller K."""
    usable = [r for r in records
              if r.get("BIC") is not None and np.isfinite(r["BIC"])]
    if not usable:
        return None
    return min(usable, key=lambda r: (r["BIC"], r["K"]))["K"]


def model_selection(r, ks=SELECTION_KS, *, n_starts: int = SELECTION_N_STARTS,
                    n_iter: int = SELECTION_N_ITER, seed_base: int = HMM_SEED,
                    reference: int = 2, verbose: bool = False) -> list[dict]:
    """Fit one Gaussian HMM per K and return their information criteria.

    ``r`` is passed through unscaled. Log-likelihoods are not scale-free, so the
    absolute figures depend on the units of ``r``; the differences reported as
    ``delta_BIC`` do not, because a change of units shifts every row by the same
    constant.
    """
    r = np.asarray(r, dtype=float)
    out = []
    for K in ks:
        hmm = GaussianHMM(K=K, n_starts=n_starts, n_iter=n_iter,
                          random_state=seed_base + K).fit(r)
        rec = {
            "K": int(K),
            "logL": float(hmm.log_likelihood_),
            "n_params": n_free_parameters(K),
            "AIC": float(hmm.aic()),
            "BIC": float(hmm.bic(len(r))),
            "sigma_bps_per_hour": sorted(float(s) * 1e4 for s in hmm.sigma),
            "seed": int(seed_base + K),
        }
        out.append(rec)
        if verbose:
            print(f"  K={K}  logL={rec['logL']:12.2f}  BIC={rec['BIC']:12.2f}  "
                  f"sigma={[round(s, 1) for s in rec['sigma_bps_per_hour']]}",
                  flush=True)

    base = next((x["BIC"] for x in out if x["K"] == reference), None)
    for rec in out:
        rec["delta_BIC"] = None if base is None else rec["BIC"] - base
    return out
